global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "kafka"
    static_configs:
      - targets: ["kafka1:7071"]

  - job_name: "producer"
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: "traffic_metrics"
    static_configs:
      - targets: ["host.docker.internal:9000"]
